name 'oci_caas_pci_tomcat'
maintainer 'Jon DeCamp (OCI CaaS)'
maintainer_email 'jon.dcamp@oracle.com'
license 'Universal Permissive License v1.0'
description 'Installs/Configures oci_caas_pci_tomcat'
version '0.3.1'
chef_version '>= 16.0'

depends 'oci_caas_base'
depends 'firewalld'
depends 'tomcat'
depends 'wazuh_agent'

issues_url 'https://github.com/oracle-quickstart/oci-caas-pci-tomcat/issues'
source_url 'https://github.com/oracle-quickstart/oci-caas-pci-tomcat'